# Example config.yaml
ollama:
  host: http://localhost:11434
  model: codellama:7b

github:
  token: YOUR_GITHUB_TOKEN_HERE  # Set via GITHUB_TOKEN environment variable

server:
  port: 5000 

# Logging configuration (Loguru)
logging:
  log_file: ollama_server.log   # Recommended: set via OLLAMA_LOG_FILE env var
  rotation: 10 MB               # Log rotation size
  retention: 10 days            # How long to keep logs
  compression: zip              # Compress old logs

# API key for authentication (set via env var in production)
api:
  key: YOUR_API_KEY_HERE        # Recommended: set via OLLAMA_API_KEY env var 